# Generated by Django 4.0.4 on 2022-06-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varierdad', models.CharField(max_length=40)),
                ('filtrado', models.CharField(max_length=40)),
                ('barista', models.CharField(max_length=40)),
                ('origen', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('cocinero', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Postres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('pastelero', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Quesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('origen', models.CharField(max_length=40)),
                ('pasteurizado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=40)),
                ('origen', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('temperatura', models.IntegerField()),
            ],
        ),
    ]
